### ISSUE TITLE
Change the test/test_klt.py

### ISSUE THREAD

**Issue by YoungHunCho** [konltk/konlp#12]
현재 test 조건이 잘못 되어 있습니다.
test조건을 바꿀 예정입니다.

**Comment by hyunyoung2** [comment]
it is done at https://github.com/konltk/konlp/blob/master/konlp/test/test_klt_kma.py

**Comment by YoungHunCho** [comment]
수정 하였습니다. [b3c1734771d73d7a74d5486c73e25404dfa8a10e](https://github.com/konltk/konlp/commit/b3c1734771d73d7a74d5486c73e25404dfa8a10e)
